# Scikit - Learn

In [34]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#### train_test_split:
    
    Split arrays or matrices into random train and test subsets

#### Create Model

In [37]:
model = LinearRegression(normalize=True)

#### Create Data

In [38]:
X, y = np.arange(10).reshape((5,2)), range(5)

In [39]:
X                                         # Actual Features

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
list(y)                                 # Actual Labels

[0, 1, 2, 3, 4]

#### Make Training Set and Testing Set

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [42]:
X_train            # Training Input

array([[0, 1],
       [4, 5],
       [6, 7]])

In [43]:
y_train           # Training Output

[0, 2, 3]

In [44]:
X_test           # Testing Input

array([[8, 9],
       [2, 3]])

In [45]:
y_test          # Testing Output

[4, 1]

#### Train / Fit our model on the Training Data

In [46]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

#### Predict Test Data from our Model

In [47]:
prediction = model.predict(X_test)

In [48]:
prediction

array([4., 1.])

In [49]:
y_test

[4, 1]

In [51]:
prediction == y_test

array([ True,  True])

#### Score of our Model:
    
    Score is between 0 and 1

In [59]:
model.score(X_test, y_test)

1.0