# NumPy Arrays

### Import NumPy

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

### define array()

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange()

In [9]:
np.arange(0,11)                      # Work like range()
                                     # Create 1-D Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros

In [11]:
np.zeros(3)               # single () means 1-D Array

array([0., 0., 0.])

In [12]:
np.zeros(5,dtype = int)       #By default it will generate float type
                              # In order to get int type we have to define it in 'dtype='

array([0, 0, 0, 0, 0])

In [13]:
np.zeros(5,dtype = float)

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros((5,3))           # (rows,column)
                          # double (()) means 2-D Array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### ones()

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.ones((3,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### linspace()

In [48]:
np.linspace(0,5,10)     #(start,stop,num)                #It return 1-D Array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### eye()

In [18]:
np.eye(4)               #Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [49]:
# 1-D Array has one ([]) brackets
# 2-D Array has two ([[]]) brackets

### random

In [20]:
np.random.rand(5)                  #Craete a 1-D Array of Random Numbers between 0 to 1

array([0.96530734, 0.56275268, 0.68946879, 0.21988686, 0.48005136])

In [21]:
np.random.rand(5,5)               #Craete a 2-D Array of Random Numbers between 0 to 1

array([[0.81743907, 0.83230864, 0.7157458 , 0.88482511, 0.10144734],
       [0.75152544, 0.73091086, 0.69551825, 0.71554882, 0.26378811],
       [0.0587535 , 0.71862519, 0.08876879, 0.78205109, 0.0689275 ],
       [0.46646871, 0.8428123 , 0.88681658, 0.3664512 , 0.87766006],
       [0.91064505, 0.49502   , 0.78764414, 0.07280939, 0.18155808]])

In [22]:
np.random.randn(2)            
# Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

array([0.42321193, 0.88476817])

In [23]:
np.random.randn(4,4) 

array([[ 0.01938987, -1.28455652,  0.3326948 ,  0.65916262],
       [ 0.34602164, -0.72335609, -2.05587044,  0.95569445],
       [ 0.48185352,  1.23729925, -1.20459745,  1.48914768],
       [-0.7406121 ,  0.86643512, -1.78975163, -0.81735018]])

In [24]:
np.random.randint(1,100)        # Return random number between given numbers

38

In [25]:
np.random.randint(1,100,10)    # Return numbers of random number

array([48, 32, 69, 31, 19, 35, 64, 77, 59, 56])

In [26]:
arr = np.arange(25)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### reshape()

In [28]:
arr.reshape(5,5)                     #Reshape the array into given rows and column

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr = np.random.randint(0,100,10)

In [51]:
ranarr

array([84, 47, 69, 50, 37, 70,  0, 35, 12, 65])

### min() and max()

In [31]:
ranarr.max()                      # Maximum        

84

In [32]:
ranarr.min()                     # Minimum

0

In [52]:
ranarr

array([84, 47, 69, 50, 37, 70,  0, 35, 12, 65])

### argmin() and agrmax()

In [34]:
ranarr.argmax()         # Return the index location of Maximum number

0

In [35]:
ranarr.argmin()        # Return the index location of Maximum number

6

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### shape() and reshape()

In [37]:
arr.shape               # Tell the shape of an array

(25,)

In [38]:
arr2 = arr.reshape(5,5)

In [39]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.shape                    

(25,)

In [54]:
arr2.shape

(5, 5)

### dtype()

In [42]:
arr.dtype               # Return data type

dtype('int32')