# NumPy Array Indexing

In [22]:
import numpy as np

## Indexing in 1-D Array

In [23]:
arr = np.arange(0,11)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[8]                           # Index Value
                                 # same as in normal Python

8

In [26]:
arr[1:5]

array([1, 2, 3, 4])

In [27]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [28]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [29]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### Broadcasting in Array

In [30]:
arr[0:5] = 100                 # multiple assignment is possible
                              # but in Python List it can only be able to do this by iteration
                             # means one by one

In [31]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [32]:
lst = [0,1,2,3,4,5,6,7,8,9]

In [33]:
lst[0:5]

[0, 1, 2, 3, 4]

In [34]:
lst[0:5] = 100

TypeError: can only assign an iterable

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
slice_of_arr = arr[0:6]

In [38]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [39]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [40]:
slice_of_arr[:] = 99                     #Broadcasting full array

In [41]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [42]:
arr                                   # It also change the original array
                                     # It does that in order to avoid memory issues

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
arr_copy = arr.copy()

In [44]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [45]:
arr_copy[0:6] = range(0,6)

In [46]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr                           # copy method doesn't change anything on the original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing in 2-D Array

In [48]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [49]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

#### Double Bracket Method of grabing element

In [50]:
arr_2d[0]

array([ 5, 10, 15])

In [51]:
arr_2d[0][0]

5

In [52]:
arr_2d[0][2]

15

In [53]:
arr_2d[1][1]

25

In [54]:
arr_2d[2][1]

40

#### Single Bracket Method of grabing element

In [55]:
arr_2d[2,1]

40

In [56]:
arr_2d[0,2]

15

In [57]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [59]:
arr_2d[:2,1:]                             #a[rows,column]

array([[10, 15],
       [25, 30]])

In [60]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

### Conditional Selectional

In [62]:
arr = np.arange(1,11)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
bool_arr = arr > 5

In [65]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [66]:
arr[bool_arr]                      #Passing bool_arr will only provide the array which is true

array([ 6,  7,  8,  9, 10])

##### OR

In [67]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [68]:
arr[arr < 3]

array([1, 2])

In [69]:
arr_2 = np.arange(50).reshape(5,10)

In [84]:
arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

###### try to grabe 21 to 27

In [86]:
arr_2[2, 1:8]

array([21, 22, 23, 24, 25, 26, 27])

##### try to grab 11 to 37

In [88]:
arr_2[1:4, 1:8]

array([[11, 12, 13, 14, 15, 16, 17],
       [21, 22, 23, 24, 25, 26, 27],
       [31, 32, 33, 34, 35, 36, 37]])

##### try to rab 13,14 and 23,24

In [73]:
arr_2[1:3 , 3:5]

array([[13, 14],
       [23, 24]])

##### try to grab 18,28,38

In [74]:
arr_2[1:4 , 8]

array([18, 28, 38])

### Fancy Indexing

In [75]:
arr = np.zeros((10,10), dtype = int)

In [89]:
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [95]:
arr.shape[1]

10

In [78]:
arr_length = len(arr)

In [79]:
arr_length

10

In [80]:
for i in range(arr_length):
    arr[i] = i

In [81]:
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [82]:
arr[[2,4,6,8]]                       #This is Fancy Indexing
                                    # Allow us to grab any no. of rows

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [83]:
arr[[1,2,5]]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])